spring.application.name=EBearSocket
spring.mustache.suffix=.html
server.port=9191

management.endpoints.web.exposure.include=health,info,prometheus
spring.jpa.properties.hibernate.format_sql=true
spring.profiles.include=secret
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=eCommerce
#spring.rabbitmq.password=eCommerce
#spring.rabbitmq.virtual-host=/
